USE g1dbsor;

#DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS
(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PRO INTEGER NOT NULL,
    NOMBRE_PRO VARCHAR(250) NOT NULL,
    ESTADO_PRO VARCHAR(8) NOT NULL
);

#DROP TABLE IF EXISTS MOTIVOS_CANCELACION;
CREATE TABLE MOTIVOS_CANCELACION
(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_MOT INTEGER NOT NULL,
    DESCRIPCION_MOT VARCHAR(250) NOT NULL,
    ESTADO_MOT VARCHAR(8) NOT NULL
);

#DROP TABLE IF EXISTS CALIFICACION_SC;
CREATE TABLE CALIFICACION_SC
(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CAL INTEGER NOT NULL,
    NOMBRE_CAL VARCHAR(20) NOT NULL
);

#DROP TABLE IF EXISTS POLIZAS;
CREATE TABLE POLIZAS
(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_PLZ INTEGER  NOT NULL ,
	ESTADO_PLZ VARCHAR (20)  NOT NULL ,
	ID_PRO_PLZ INTEGER  NOT NULL ,
	INICIO_VIGENCIA_PLZ DATE NOT NULL,
	FIN_VIGENCIA_PLZ DATE  NOT NULL ,
	FECHA_CAN_PLZ DATE NULL ,
	VALOR_SEGURO_PLZ DECIMAL (8,2) NOT NULL ,
	ID_MOT_PLZ INTEGER NULL
);

#DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES
(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLI INTEGER NOT NULL, 
	IDENTIFICACION_CLI VARCHAR (20) NOT NULL , 
	NOMBRE_CLI VARCHAR (250) NOT NULL ,
    APELLIDO_CLI VARCHAR (250) NOT NULL ,
	TIPO_CLI VARCHAR (50) NOT NULL , 
	SUCURSAL_CLI VARCHAR(50) NOT NULL , 
	APS_CLI VARCHAR (250) , 
	ID_PLZ_CLI INTEGER NOT NULL , 
	ID_CAL_CLI INTEGER NOT NULL
);

ALTER TABLE POLIZAS 
    ADD CONSTRAINT POLIZA_PRODUCTO_FK FOREIGN KEY 
    ( 
        ID_PRO_PLZ
    ) 
    REFERENCES PRODUCTOS 
    ( 
        ID
    );
    
ALTER TABLE POLIZAS 
    ADD CONSTRAINT POLIZA_MOTIVO_FK FOREIGN KEY 
    ( 
        ID_MOT_PLZ
    ) 
    REFERENCES MOTIVOS_CANCELACION 
    ( 
        ID
    );
    
ALTER TABLE CLIENTES 
    ADD CONSTRAINT CLIENTE_POLIZA_FK FOREIGN KEY 
    ( 
        ID_PLZ_CLI
    ) 
    REFERENCES POLIZAS 
    ( 
        ID
    );
    
ALTER TABLE CLIENTES
    ADD CONSTRAINT CLIENTE_CALIFICACION_FK FOREIGN KEY 
    ( 
        ID_CAL_CLI
    ) 
    REFERENCES CALIFICACION_SC 
    ( 
        ID
    );